### PR TITLE
Improve code generation for constants.

### PR DESCRIPTION
**Pull request by Cryptjar**
This PR adds alphabetic sorting of all constants first by group then subgroup and then by name.
This will make diffs of the `src/constants.rs` file simpler in the future (i.e. they will be no longer randomly shuffled).

Additionally, each constant now has documentation containing the name, the Unicode symbol/grapheme, and the list of Unicode code points.

### CODE REVIEW

**Comment by orhanbalci** [comment]
Hi there;
Sorry for late response. I think this is a good idea. Just one thing I could not understand is what is the middle `#[doc=""]` for?

**Comment by Cryptjar** [comment]
The `#[doc=""]` creates an empty line. This practically separates the header line (which is shown in the module overview) from the longer explanation.

For instance,  
`#[doc="artist palette 🎨"]#[doc=""]#[doc="Rendered as: 🎨 (U+1F3A8)"]`  
will be turned into  
`#[doc="artist palette 🎨\n\nRendered as: 🎨 (U+1F3A8)"]`
which make `artist palette 🎨` the header line.

**Comment by orhanbalci** [comment]
Is it possible to see rendered documentation?

**Comment by Cryptjar** [comment]
Certainly, if you have a local version of the repository, you can simply generate and open the documentation using cargo:
```sh
cargo doc --open
```

**Pull request merged**
